UPDATE translate SET VALUE = "Créé (non approuvé)" WHERE ID = 1053068;
UPDATE translate SET VALUE = "Approuvé. Traitement des informations pour le transfert à l'entrepôt" WHERE ID = 1053069;
UPDATE translate SET VALUE = "Informations transférées à l'entrepôt. L'envoi se prépare pour être récupéré. En attente du ramassage à l'entrepôt à l'arrivée" WHERE ID = 1053070;
UPDATE translate SET VALUE = "Expédié" WHERE ID = 1053071;
UPDATE translate SET VALUE = "Annulé" WHERE ID = 1053072;
UPDATE translate SET VALUE = "Demande acceptée en ligne. Traitement des informations à envoyer au système comptable" WHERE ID = 1053073;
UPDATE translate SET VALUE = "Envoyé au système comptable" WHERE ID = 1053074;
UPDATE translate SET VALUE = "Pas ordonné" WHERE ID = 1053075;
UPDATE translate SET VALUE = "En cours de livraison" WHERE ID = 1053076;
UPDATE translate SET VALUE = "En stock" WHERE ID = 1053077;
UPDATE translate SET VALUE = "Expédié" WHERE ID = 1053078;
UPDATE translate SET VALUE = "Reçu de paiement" WHERE ID = 1053079;
UPDATE translate SET VALUE = "Remboursement" WHERE ID = 1053080;
UPDATE translate SET VALUE = "Compensation" WHERE ID = 1053081;
UPDATE translate SET VALUE = "Autre" WHERE ID = 1053082;
UPDATE translate SET VALUE = "Enlèvement par contrepartie ou société de transport" WHERE ID = 1053083;
UPDATE translate SET VALUE = "Livraison à l'adresse" WHERE ID = 1053084;
UPDATE translate SET VALUE = "Livraison au point de récupération de la société de transport" WHERE ID = 1053085;
UPDATE translate SET VALUE = "Demande de pièces de rechange" WHERE ID = 1053086;
UPDATE translate SET VALUE = "Messages sur le portail" WHERE ID = 1053087;
UPDATE translate SET VALUE = "E-mail" WHERE ID = 1053088;
UPDATE translate SET VALUE = "Brouillon" WHERE ID = 1053089;
UPDATE translate SET VALUE = "Demande acceptée en ligne. Les informations sont en cours de préparation pour être envoyées au système comptable" WHERE ID = 1053090;
UPDATE translate SET VALUE = "Envoyé au système comptable" WHERE ID = 1053091;
UPDATE translate SET VALUE = "Créé (non approuvé)" WHERE ID = 1053092;
UPDATE translate SET VALUE = "Annulé" WHERE ID = 1053093;
UPDATE translate SET VALUE = "Approuvé. Les informations sont en cours de préparation pour le transfert à l'entrepôt de départ" WHERE ID = 1053094;
UPDATE translate SET VALUE = "Les informations ont été transférées à l'entrepôt. Préparation de l'expédition depuis l'entrepôt de départ" WHERE ID = 1053095;
UPDATE translate SET VALUE = "Complété. Marchandises expédiées à l'entrepôt de destination" WHERE ID = 1053096;
UPDATE translate SET VALUE = "Équipement" WHERE ID = 1053097;
UPDATE translate SET VALUE = "Vaisselle et ustensiles" WHERE ID = 1053098;
UPDATE translate SET VALUE = "Question à propos du  produit " WHERE ID = 293744;
UPDATE translate SET VALUE = "Question à propos de la commande" WHERE ID = 293745;
UPDATE translate SET VALUE = "Question à propos de la livraison " WHERE ID = 293746;
UPDATE translate SET VALUE = "Addendum à la plainte/réclamation" WHERE ID = 293747;
UPDATE translate SET VALUE = "Question sur la demande d'expédition" WHERE ID = 293748;
UPDATE translate SET VALUE = "Question sur les fonctionnalités du site (aux développeurs)" WHERE ID = 293749;
