INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"shipment_status","CODE","Créé (non approuvé)",1);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"shipment_status","CODE","Approuvé. Traitement des informations pour le transfert à l'entrepôt",2);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"shipment_status","CODE","Informations transférées à l'entrepôt. L'envoi se prépare pour la cueillette. Attendra le ramassage à l'entrepôt à l'arrivée",3);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"shipment_status","CODE","Expédié",4);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"shipment_status","CODE","Annulé",5);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"shipment_status","CODE","Candidature acceptée en ligne. Traitement des informations à envoyer au système comptable",6);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"shipment_status","CODE","Envoyé au système comptable",7);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"or_order_product_status","NAME","Pas ordonné",1);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"or_order_product_status","NAME","En livraison",2);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"or_order_product_status","NAME","En stock",3);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"or_order_product_status","NAME","Expédié",4);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"receipts_actions","NAME","Reçu de paiement",1);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"receipts_actions","NAME","Remboursement",2);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"receipts_actions","NAME","Compensation",3);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"receipts_actions","NAME","Autre",4);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"or_delivery_status","TEXT","Enlèvement par contrepartie ou société de transport",1);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"or_delivery_status","TEXT","Livraison à l'adresse",2);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"or_delivery_status","TEXT","Livraison au point de la société de transport",3);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"or_delivery_status","TEXT","Livraison Y",4);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"subscriptions_channels","NAME","Messages sur le portail",1);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"subscriptions_channels","NAME","E-mail",2);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"returns_statuses","NAME","Brouillon",1);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"returns_statuses","NAME","Candidature acceptée en ligne. Les informations sont en cours de préparation pour être envoyées au système comptable",2);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"returns_statuses","NAME","Envoyé au système comptable",3);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"returns_statuses","NAME","Créé (non approuvé)",4);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"returns_statuses","NAME","Annulé",5);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"returns_statuses","NAME","Approuvé. Les informations sont en cours de préparation pour le transfert à l'entrepôt de départ",6);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"returns_statuses","NAME","Les informations ont été transférées à l'entrepôt. Préparation de l'expédition depuis l'entrepôt de départ",7);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"returns_statuses","NAME","Complété. Marchandises expédiées à l'entrepôt de destination",8);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"pr_brands_type","NAME","Équipement",1);
INSERT INTO translate (`LANG`,`TABLE`,`FIELD`,`VALUE`,`ROW_ID`) VALUES (5,"pr_brands_type","NAME","Vaisselle et ustensiles",2);
