INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 5, 'DELIVERY_BY_TRANSPORT_COMPANY', 'Livraison automatique par entreprise de transport');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 3, 'DELIVERY_BY_TRANSPORT_COMPANY', 'Auto delivery by transport company');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 2, 'DELIVERY_BY_TRANSPORT_COMPANY', 'Самовывоз транспортной компанией');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 5, 'DELIVERY_BY_SELF', 'Voiture de particulier');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 3, 'DELIVERY_BY_SELF', 'Private person’s auto');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 2, 'DELIVERY_BY_SELF', 'Самовывоз частным лицом');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 5, 'TEST_TEST_TEST', 'test');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 3, 'TEST_TEST_TEST', 'test');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 2, 'TEST_TEST_TEST', 'тест');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 5, 'CAR_INFO', 'Numéro et marque de l’État');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 3, 'CAR_INFO', 'State car number and car brand');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 2, 'CAR_INFO', 'Государственный номер авто и марка авто');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 5, 'DOCUMENT_NUMBER', 'Numéro de série/document');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 3, 'DOCUMENT_NUMBER', 'Series/document number');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 2, 'DOCUMENT_NUMBER', 'Серия/номер документа');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 5, 'DRIVER_DOCUMENT', 'Document du conducteur');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 3, 'DRIVER_DOCUMENT', 'Driver’s document');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 2, 'DRIVER_DOCUMENT', 'Документ водителя');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 5, 'FIO_DRIVER', 'Le nom du chauffeur');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 3, 'FIO_DRIVER', 'Driver’s name');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 2, 'FIO_DRIVER', 'ФИО водителя');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 5, 'PASSPORT', 'Passeport');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 3, 'PASSPORT', 'Passport');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 2, 'PASSPORT', 'Паспорт');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 5, 'DRIVE_LICENSE', 'Permis de conduire');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 3, 'DRIVE_LICENSE', 'Driver''s license');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 2, 'DRIVE_LICENSE', 'Водительские права');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 5, 'GO_TO_SHIPMENTS_GROUP', 'Accédez au groupe de commandes à expédier');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 3, 'GO_TO_SHIPMENTS_GROUP', 'Go to the group of orders for shipment');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 2, 'GO_TO_SHIPMENTS_GROUP', 'Перейти к группе заявок на отгрузку');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 5, 'SIPMENTS_GROUP', 'Groupe de commandes à expédier');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 3, 'SIPMENTS_GROUP', 'Group of shipment requests');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 2, 'SIPMENTS_GROUP', 'Группа заявок на отгрузку');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 5, 'SELECT_SHIPMENT_APPEAL', 'Sélectionnez une demande d''expédition');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 3, 'SELECT_SHIPMENT_APPEAL', 'Select a shipment request');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 2, 'SELECT_SHIPMENT_APPEAL', 'Выберите заявку на отгрузку');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 5, 'COND_SHIPMENT', 'Statut de l''expédition');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 3, 'COND_SHIPMENT', 'Shipment Status');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 2, 'COND_SHIPMENT', 'Состояние отгрузки');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 5, 'APPEAL_PRODUCTS', 'Produits dans la demande d''expédition');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 3, 'APPEAL_PRODUCTS', 'Products in the shipment request');
INSERT INTO `translate_interface` (site_id, lang_id, `key`, value) VALUES(1, 2, 'APPEAL_PRODUCTS', 'Товары в заявке на отгрузку');